# Generated by Django 4.2.1 on 2023-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepallapp', '0002_alter_note_editor_alter_stickynote_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='label',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
