# Generated by Django 4.2.1 on 2023-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepallapp', '0003_alter_stickynote_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='color',
            field=models.CharField(max_length=30),
        ),
    ]
